.TH "cpglockd" "8" "Mar 2013" "" "Red Hat High Availability"
.SH "NAME"
cpglockd \- CPG lock server
.SH "DESCRIPTION"
.PP 
.B cpglockd
utilizes the extended virtual synchrony features of the Corosync
Cluster Engine to implement a simplistic, distributed lock server.
.SH "COMMAND LINE OPTIONS"
.IP \-f
Operate in the foreground mode; do not daemonize
.IP \-h
Print command line usage.

.SH "SEE ALSO"
corosync(8)
